import logging
import os


"""
CONSTANTS::
    GPIO::
        GPIO_INPUT = "in"
        GPIO_OUTPUT = "out"
        GPIO_ON = 1
        GPIO_OFF = 0
    LOGGER::
        LOGGER_STATUS = 0
        LOGGER_EVENT = 1
        LOGGER_PRIORITY_LEVEL = 60
"""
#GPIO CONSTANTS
GPIO_INPUT = "in"
GPIO_OUTPUT = "out"
GPIO_HIGH = 1
GPIO_LOW = 0


#LOGGER CONSTANTS
LOGGER_STATUS = 0
LOGGER_EVENT = 1
LOGGER_PRIORITY_LEVEL = 60
