sudo: false

language: python

python:
  - 3.6

install: 
  - pip install pylint

script: 
  - pylint control/src control/tests client/src client/tests server/src server/tests 
  - python enforcer.py

